version: "3.9"
services:

  bla:
    container_name: bla_container
    hostname: 'bla'
    image: selenium/hub
    networks:
      - test_net
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
    volumes:
      - /dev/shm:/dev/shm

  chrome:
      image: selenium/node-chrome:latest
      shm_size: 2gb
      depends_on:
        - bla
      networks:
        - test_net
      volumes:
        - /dev/shm:/dev/shm
      environment:
        - SE_EVENT_BUS_HOST=bla
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_NODE_OVERRIDE_MAX_SESSIONS=true
        - SE_NODE_MAX_SESSIONS=10
      ports:
        - "9005:9005"

  worker:
    container_name: worker_container
    image: my-image:1
    networks:
      - test_net
    entrypoint:
      - /tmp/run.sh
    depends_on:
      - bla

networks:
  test_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16